rvm:
  - "2.1.0"

script:
  - "RAILS_ENV=test bundle exec rake db:migrate --trace"
  - "bundle exec rspec"

before_script:
  - cp config/database.travis.yml config/database.yml

before_install:
  - gem install bundler -v '= 1.5.1'
